services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - alc-network
    restart: unless-stopped

  backend:
    image: serena2z/alc:backend
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - alc-network
    restart: unless-stopped

  frontend:
    image: serena2z/alc:frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - alc-network
    restart: unless-stopped

networks:
  alc-network:

volumes:
  backend-dbstore: