[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef
GROQ = "" 
ANTHROPIC = "" 

[API_ENDPOINTS]
SEARXNG = "http://localhost:4000" # SearxNG API URL