use_default_settings: true

search:
  safe_search: 0
  autocomplete: ''
  default_lang: 'auto'
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: go
    use_mobile_ui: true 
    # Remove site filtering from settings since we're adding it in the query
    # search_url: https://www.google.com/search?q={query}
    disabled: false

  # add qwant engine
  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false

  # Configure DuckDuckGo with site filtering
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    # Remove site filtering from settings
    # search_url: https://duckduckgo.com/?q={query}
    disabled: false

  # Keep PubMed as it's a valuable medical research database
  - name: pubmed
    engine: pubmed
    shortcut: pub
    disabled: false

  # Keep Google Scholar for academic papers
  - name: google scholar
    engine: google_scholar
    shortcut: gos
    disabled: false

  # Other engines
  - name: bing
    engine: bing
    shortcut: bi
    disabled: true
  
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: true

# Keep other necessary settings from your original config
general:
  debug: true
  instance_name: 'searxng'
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true

server:
  port: 8888
  limiter: false
  public_instance: false
  bind_address: '127.0.0.1'
  secret_key: 'your_secret_key_here'
  base_url: /